import type { Patient } from '@/types';

export const mockPatients: Patient[] = [
  {
    id: '1',
    name: 'Robert Johnson',
    age: 62,
    sex: 'male',
    symptoms: ['Dizziness', 'Slurred Speech', 'Weakness in Left Arm'],
    triageLevel: 'level1',
    medicalHistory: 'Diabetes (Type 2, diagnosed 15 years ago). Hypertension (diagnosed 10 years ago). Smoker for 30 years (1 pack per day). History of high cholesterol. No previous strokes or major surgeries.',
    visitReason: 'Sudden onset of dizziness, difficulty speaking, and weakness in the left arm. Symptoms started 45 minutes ago while watching television. No prior history of similar episodes.',
    timestamp: '2025-03-20T05:45:00Z',
    aiConfidence: 88,
    aiDiagnosis: 'High probability of acute ischemic stroke. Immediate neurological evaluation and possible administration of thrombolytic therapy required. Recommended CT scan and blood tests for further assessment.',
  },
  {
    id: '2',
    name: 'John Doe',
    age: 45,
    sex: 'male',
    symptoms: ['Chest Pain', 'Shortness of Breath', 'Sweating', 'Nausea'],
    triageLevel: 'level1',
    medicalHistory: 'Hypertension (diagnosed 5 years ago), Hyperlipidemia. Previous myocardial infarction 2 years ago, treated with stent placement. No known allergies. Family history of heart disease (father had a fatal heart attack at 52).',
    visitReason: 'Experiencing severe, crushing chest pain radiating to the left arm and jaw, accompanied by nausea and shortness of breath. Pain started 1 hour ago after light physical activity. No relief with rest or deep breathing.',
    timestamp: '2025-03-20T06:30:00Z',
    aiConfidence: 92,
    aiDiagnosis: 'High likelihood of acute coronary syndrome (ACS), possible myocardial infarction (MI). Immediate ECG, cardiac enzyme tests, and emergency cardiology consult recommended. Consider aspirin and nitroglycerin administration.',
  },
  {
    id: '3',
    name: 'David Wilson',
    age: 55,
    sex: 'male',
    symptoms: ['Severe Lower Back Pain', 'Limited Mobility'],
    triageLevel: 'level3',
    medicalHistory: 'Chronic arthritis (diagnosed 8 years ago), previous lumbar disc herniation (treated conservatively). Mild obesity (BMI: 31). No previous surgeries.',
    visitReason: 'Severe lower back pain that started suddenly this morning while lifting a heavy box. Pain worsens with movement and does not improve with rest. No numbness or tingling in the legs.',
    timestamp: '2025-03-20T06:00:00Z',
    aiConfidence: 82,
    aiDiagnosis: 'Possible acute lumbar strain or disc herniation. Recommend MRI if symptoms persist or worsen. Pain management and physical therapy referral suggested.',
  },
  {
    id: '4',
    name: 'Jane Smith',
    age: 28,
    sex: 'female',
    symptoms: ['Fever', 'Cough', 'Shortness of Breath'],
    triageLevel: 'level2',
    medicalHistory: 'Asthma (diagnosed at age 10, controlled with inhalers). No known allergies. No history of pneumonia or hospitalizations.',
    visitReason: 'Developed high fever (39°C) and persistent, productive cough over the past two days. Reports mild shortness of breath and wheezing. No chest pain or previous similar episodes.',
    timestamp: '2025-03-20T07:15:00Z',
    aiConfidence: 85,
    aiDiagnosis: 'Likely upper respiratory tract infection with asthma exacerbation. Consideration for pneumonia based on symptoms. Recommend chest X-ray, oxygen saturation monitoring, and possible bronchodilator therapy.',
  },
  {
    id: '5',
    name: 'Maria Garcia',
    age: 35,
    sex: 'female',
    symptoms: ['Headache', 'Mild Nausea', 'Sensitivity to Light'],
    triageLevel: 'level4',
    medicalHistory: 'No chronic medical conditions. No known allergies. No history of migraines.',
    visitReason: 'Persistent, throbbing headache since yesterday, localized to the temples. Worsens with bright lights and noise but improves slightly with rest. No visual disturbances or loss of consciousness.',
    timestamp: '2025-03-20T08:00:00Z',
    aiConfidence: 78,
    aiDiagnosis: 'Likely tension headache, possible early-stage migraine. Recommend hydration, rest, and over-the-counter pain relief. If symptoms persist or worsen, further neurological assessment needed.',
  }
];
